spring:
    datasource:
        url: jdbc:postgresql://postgresqldb:5432/clear-solutions
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        date-format: dd.MM.yyyy
        serialization:
            write-dates-as-timestamps: false

user:
    age:
        required: 18
